### ISSUE TITLE
[Object recolorizer 0.1.3] Issue with Gdevelop version 5.3.198

### ISSUE THREAD

**Issue by ClaryuB** [GDevelopApp/GDevelop-extensions#1244]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/GDevelopApp/GDevelop-extensions/issues)

### Enter the name of the extension

Object recolorizer 0.1.3

### Describe the bug of the extension

TypeError: sprite._animations is not iterable
    at Object.GDJSInlineCode [as userFunc0xc34160] (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/gdjs-evtsext__recolorizer__spriterecolorizer.js:78:36)
    at Object.gdjs.evtsExt__Recolorizer__SpriteRecolorizer.SpriteRecolorizer.onCreatedContext.eventsList0 (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/gdjs-evtsext__recolorizer__spriterecolorizer.js:123:91)
    at SpriteRecolorizer.gdjs.evtsExt__Recolorizer__SpriteRecolorizer.SpriteRecolorizer.onCreated (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/gdjs-evtsext__recolorizer__spriterecolorizer.js:192:91)
    at r.onCreated (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/runtimeobject.js:1:3072)
    at new r (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/spriteruntimeobject.js:1:495)
    at createObject (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/RuntimeInstanceContainer.js:1:5517)
    at createObjectsFrom (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/RuntimeInstanceContainer.js:1:1755)
    at c.loadFromScene (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/runtimescene.js:1:2136)
    at r._loadNewScene (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/scenestack.js:1:1589)
    at r.push (file:///C:/Users/bclau/AppData/Local/Temp/GDTMP--1/preview/scenestack.js:1:1364)

### Steps to reproduce

1. Use Object recolorizer in the current scene
2. Launch the game
3. Game crash using the new gdevelop version 5.3.198

### GDevelop platform

Desktop, Web, Mobile

### GDevelop version

5.3.198

### Platform info

<details>

*OS (e.g. Windows, Linux, macOS, Android, iOS)*
>

*OS Version (e.g. Windows 10, macOS 10.15)*
>

*Browser(For Web) (e.g. Chrome, Firefox, Safari)*
>

*Device(For Mobile) (e.g. iPhone 12, Samsung Galaxy S21)*
>

</details>

**Comment by D8H** [comment]
Thank you for reporting this issue, it's fixed by this PR:
- https://github.com/GDevelopApp/GDevelop-extensions/pull/1247
